-- ТОК / ИГЭУ — миграция поддержки, жалоб и главной страницы

-- Проверка администратора (безопасно для RLS)
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

grant execute on function public.is_admin() to authenticated;


alter table public.profiles add column if not exists hobbies text;

create table if not exists public.app_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.app_settings enable row level security;

drop policy if exists "Authenticated users can view app settings" on public.app_settings;
create policy "Authenticated users can view app settings"
on public.app_settings for select to authenticated using (true);

drop policy if exists "Admins can insert app settings" on public.app_settings;
create policy "Admins can insert app settings"
on public.app_settings for insert to authenticated with check (public.is_admin());

drop policy if exists "Admins can update app settings" on public.app_settings;
create policy "Admins can update app settings"
on public.app_settings for update to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.app_settings (key,value) values
('home_title','Общайся. Знакомься. Находи своих.'),
('home_description','ТОК создан специально для студентов ИГЭУ. Здесь всё начинается с обычной симпатии.')
on conflict (key) do nothing;

create table if not exists public.support_conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id)
);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.support_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reported_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.support_conversations enable row level security;
alter table public.support_messages enable row level security;
alter table public.reports enable row level security;

drop policy if exists "Users can view own support conversation" on public.support_conversations;
create policy "Users can view own support conversation"
on public.support_conversations for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users can create own support conversation" on public.support_conversations;
create policy "Users can create own support conversation"
on public.support_conversations for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can view support messages" on public.support_messages;
create policy "Users can view support messages"
on public.support_messages for select to authenticated
using (exists (select 1 from public.support_conversations sc where sc.id = support_messages.conversation_id and (sc.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Users can send support messages" on public.support_messages;
create policy "Users can send support messages"
on public.support_messages for insert to authenticated
with check (sender_id = auth.uid() and exists (select 1 from public.support_conversations sc where sc.id = support_messages.conversation_id and (sc.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Users can create reports" on public.reports;
create policy "Users can create reports"
on public.reports for insert to authenticated
with check (reporter_id = auth.uid() and reported_user_id <> auth.uid());

drop policy if exists "Users and admins can view reports" on public.reports;
drop policy if exists "Admins can view all reports" on public.reports;
create policy "Users and admins can view reports"
on public.reports for select to authenticated
using (reporter_id = auth.uid() or public.is_admin());

drop policy if exists "Admins can update reports" on public.reports;
create policy "Admins can update reports"
on public.reports for update to authenticated
using (public.is_admin()) with check (public.is_admin());

alter table public.support_messages replica identity full;
alter table public.reports replica identity full;
alter table public.app_settings replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'support_messages') then
    alter publication supabase_realtime add table public.support_messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'reports') then
    alter publication supabase_realtime add table public.reports;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'app_settings') then
    alter publication supabase_realtime add table public.app_settings;
  end if;
end $$;
